name: Build and Deploy Dockerized App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.AZURE_PRIVATE_KEY }}

      # Step 3: Deploy to Azure VM
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@172.206.82.46 << 'EOF'
            # Navigate to project folder
            cd /home/azureuser/ateeq/ateeq-devops-exam

            # Pull the latest code
            git reset --hard
            git pull origin main

            # Rebuild and restart Docker containers
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
